[tool.poetry]
name = "mangaapi"
version = "0.1.0"
description = "A Python-based web scraping API built with FastAPI that provides easy access to manga contents."
authors = ["tokitou-san <tokitousan2005@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.28.1"}
requests = "^2.31.0"
pydantic-core = "^2.17.0"
anyio = "^4.2.0"
black = "^24.3.0"
pre-commit = "^3.6.0"
jinja2 = "^3.1.3"
markdown = "^3.6"
selectolax = "^0.3.21"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
